### ISSUE TITLE
looks promising, would love to try out your code!

### ISSUE THREAD

**Issue by zozobozo** [YanchaoYang/FDA#1]
Hi,

Pretty cool work! Any updates on when the code would be released?

Thanks!
Z.

**Comment by shyanguan** [comment]
Me too

**Comment by kjjeong78** [comment]
I have done the FDA with python.
However, there are some artifact because we transform the each channel r, g, b.
How do you remove that?

**Comment by dongyangcai** [comment]
looking forward to your code!

**Comment by YanchaoYang** [comment]
Guys, thanks for your interest. I have just uploaded the source code and the trained models. Please have fun!

**Comment by YanchaoYang** [comment]
> I have done the FDA with python.
> However, there are some artifact because we transform the each channel r, g, b.
> How do you remove that?
> 
> ![image](https://user-images.githubusercontent.com/32060228/85504673-70c28f00-b627-11ea-8e94-a448d825e59a.png)

Did you do any normalization or mean subtraction before FDA?  If so, you may want to remove these preprocessings.

Also, I have released the python version of FDA, and its usage in FDA_demo.py. Could you take a look and see if this will be useful?

**Comment by kjjeong78** [comment]
> 
> 
> > I have done the FDA with python.
> > However, there are some artifact because we transform the each channel r, g, b.
> > How do you remove that?
> > ![image](https://user-images.githubusercontent.com/32060228/85504673-70c28f00-b627-11ea-8e94-a448d825e59a.png)
> 
> Did you do any normalization or mean subtraction before FDA? If so, you may want to remove these preprocessings.
> 
> Also, I have released the python version of FDA, and its usage in FDA_demo.py. Could you take a look and see if this will be useful?

Thank you. I will try to test with your code and check my code what is a cause.

**Comment by zozobozo** [comment]
thanks!!
