### ISSUE TITLE
Question about second SST round 

### ISSUE THREAD

**Issue by LeonBre** [YanchaoYang/FDA#12]
Hello and thank you for your great work :-)
I have a question about the performance boost of around 1,5% after the second SST round. 
How do you achieve that? I tried it out twice and both times my model has a worse performance than after the first SST round.
Do I have to change something in the settings or do I just have to retry it a couple more times.

**Comment by YanchaoYang** [comment]
which epoch you are choosing for validation?

**Comment by LeonBre** [comment]
Thank you for your fast reply!
I did not touch the settings for the number of steps. The validation is done after 100000 steps. Do I have to use more steps here?

**Comment by YanchaoYang** [comment]
Yeah, I guess that is the problem. So during SST you may want to use early ckpts, to prevent overfitting to wrong pseudo labels.

**Comment by LeonBre** [comment]
Ok I will try that.

Thanks :+1:

**Comment by scalyvladimir** [comment]
Could you pleasy clarify, what authors mean by saying Round of SST?
Does it mean simply another training cycle or ?
