### ISSUE TITLE
Not able to understand this line

### ISSUE THREAD

**Issue by kaushal-py** [YanchaoYang/FDA#3]
I am not able to understand the use of this line in the entropy loss implementation. How was this derived? What is its relation to number of classes?

https://github.com/YanchaoYang/FDA/blob/b9a0cdf0bcc9b787c00e39df73eda5673706f219/model/CLS.py#L51

**Comment by YanchaoYang** [comment]
This number is the maximum entropy when assuming uniform distribution, which is to normalize the entropy been calculated.
