### ISSUE TITLE
Why convert to BGR?

### ISSUE THREAD

**Issue by BinhuiXie** [YanchaoYang/FDA#30]
https://github.com/YanchaoYang/FDA/blob/b9a0cdf0bcc9b787c00e39df73eda5673706f219/data/gta5_dataset.py#L57

**Comment by YanchaoYang** [comment]
Not so sure, I guess it is just some historical heritage from the code that we adapted.

**Comment by BinhuiXie** [comment]
Thank you for your replay.

**Comment by wangtingwei1993** [comment]
@BinhuiXie It seems that they convert the image to BGR and then restore it to RGB. The fourier module in the train.py file finally takes the RGB image as the input. However, the Fourier module in the FDA_demo.py file takes the BGR image as input. Do you know what's the difference between these two implementation?

**Comment by wangtingwei1993** [comment]
@BinhuiXie Hi, do you know why the input image of the Fourier module must be RBG images rather than the original RGB images?

**Comment by BinhuiXie** [comment]
@wangtingwei1993 Actually, I have no idea. However, through practice I have found that the FFT is independent of each channel, so it is possible that any order is feasible, i.e., BGR, RGB, or RBG and etc.

Hi. @YanchaoYang. What do you think?

**Comment by YanchaoYang** [comment]
> @wangtingwei1993 Actually, I have no idea. However, through practice I have found that the FFT is independent of each channel, so it is possible that any order is feasible, i.e., BGR, RGB, or RBG and etc.
> 
> Hi. @YanchaoYang. What do you think?

Yes, the order does not affect FDA, or the adaptation performance, it only affects the final visualization I guess.
