### ISSUE TITLE
Questions about entropy minimization

### ISSUE THREAD

**Issue by jxhuang0508** [YanchaoYang/FDA#4]
Hi, thanks for sharing your work. However, I have some questions about your work.

1. Why you introduce the entropy minimization in your work?
There is no obvious ablation study for it except Table 1. In Table 1,  beta = 0.09(T=0) == 45.01, and beta = 0.09(Ent=0) == 44.64. The previous one is with entropy loss, and latter is without entropy loss, right? If there exists only 0.37 improvements, why your utilize entropy loss in your work? It may introduce some misunderstandings.

Or you just introduce two types of self training ? entropy minimization and pseudo label retraining?

Thanks! looking forward to your reply!

**Comment by YanchaoYang** [comment]
Yes, the interpretation in Tab1 is correct. Generally, entropy minimization is used for semi-supervised learning. However, it could also be used for unsupervised domain adaptation, when two domains are nearly aligned. In this case, you can think of the source data together with its labels as the labeled data in the semi-supervised setting. So in practice, to use entropy minimization properly, you may want to enable it after some alignment has been performed.

**Comment by jxhuang0508** [comment]
Understood, thanks for your reply!
