### ISSUE TITLE
How to get best model of single Beta?

### ISSUE THREAD

**Issue by zengkaiwei** [YanchaoYang/FDA#6]
When I run train.py with  --LB=0.01 as the command you show, I get files about:
gta5_2500.pth~gta5_100000.pth, I guess you will test this file and rename the best as  gta2city_LB_0_01.pth for multiple test. But I can I find the best model of single beta?

**Comment by YanchaoYang** [comment]
I usually set "--num-steps-stop" for the learning rate scheduler to 150000, and check ckpts between 100000. But it is true that you may also want to check the ckpts around 100000 as there are some randomness for the best ckpts, or you can try multiple runs and check the best score you will get.
