### ISSUE TITLE
Questions about FDA.demo.py

### ISSUE THREAD

**Issue by zengkaiwei** [YanchaoYang/FDA#7]
I guess you use code in FDA_demo to transform original images, but when run FDA_demo.py, nothing happen and the process over in several seconds. Does FDA_demo.py really work?

**Comment by YanchaoYang** [comment]
should work, the examplar images are generated by this script, did you do a step by step check to see where the process ends? it should not take several seconds.

**Comment by Siddharth-Shrivastava7** [comment]
Yeah, it works!

**Comment by ALEX13679173326** [comment]
I have a problem 'AttributeError: module 'scipy.misc' has no attribute 'toimage' ' when I use 'scipy.misc.toimage', and then I use 'Image.fromarray'.There is a problem with the image obtained...
So how do you get the correct result?

**Comment by cvmlddev** [comment]
@ALEX13679173326 to image was discontinued after scipy 1.3, Try with an older version
